### ISSUE TITLE
expectComponent does not work with hbs rendering

### ISSUE THREAD

**Issue by AndyPyeSC** [201-created/ember-cli-acceptance-test-helpers#22]
`expectElement` works:

```javascript
test('it renders', function (assert) {
  assert.expect(1);

  this.render(hbs`
    {{#my-component class="my-component"}}
      Some text here
    {{/my-component}}
  `);

  expectElement(".my-component", 1);
});
```

We would prefer to use `expectComponent` to write this as

```javascript
test('it renders', function (assert) {
  assert.expect(1);

  this.render(hbs`
    {{#my-component}}
      Some text here
    {{/my-component}}
  `);

  expectComponent("my-component", 1);
});
```

but this fails in `Component.detectInstance`.

**Comment by bantic** [comment]
@AndyPyeSC The acceptance test helpers are intended to be used for acceptance tests (ones where `startApp()` is called and the registered test helpers are injected) — this looks like a component integration test. If the acceptance test helpers work during integration tests like this that is mostly a matter of coincidence, definitely not design, although I do think they'd be handy in a case like this. The affordances that Ember Testing provides for registering helpers would need to be improved in order to facilitate this use case.

**Comment by BryanCrotaz** [comment]
Hi @bantic from @AndyPyeSC 's boss...

We are calling `start-app` in the test setup phase, so this is essentially an acceptance test, and `expectElement` is working correctly. Thus we think this is a bug in `expectComponent`, probably in `Component.detectInstance` which is where the error occurs - it returns `false` when it should return `true`

**Comment by BryanCrotaz** [comment]
@bantic if you can give us some hints as to how this might be fixed we'd be happy to build up a PR

**Comment by BryanCrotaz** [comment]
See http://alisdair.mcdiarmid.org/2015/06/20/ember-component-integration-tests.html for what we're trying to do.

**Comment by bantic** [comment]
`expectElement` works because it is using `find` to look for the element by its CSS selector — I believe the fact that it works is sort of a coincidence of the way the `render` call works in the integration test. `render` [appends to '#ember-testing'](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L69-L70), which happens to be the app's root element, so the [default behavior of `find`](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js#L200-L206) works. `expectElement` internally just delegates to `find`. But `expectComponent` does a bit more work internally, looking through the app's registered views, and `render` does not use the app itself, so the app's registered views won't include this component.

There is an argument to be made that a component integration test is not the place to use acceptance test helpers. A component integration test is for treating your component more like a "black box" — render it and then assert that the resulting DOM looks as expected, without dealing with Ember's internals or the component's internals. The component integration tests specifically [disallow `subject`](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L40) for this reason, in fact.
